<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAsty91y\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAsty91y/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAsty91y.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAsty91y\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAsty91y\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Asty91y',
    'container.build_id' => 'a5eef105',
    'container.build_time' => 1525527634,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAsty91y');
