<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsbx8Y1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsbx8Y1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOsbx8Y1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOsbx8Y1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOsbx8Y1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Osbx8Y1',
    'container.build_id' => '51ade7ee',
    'container.build_time' => 1525690202,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsbx8Y1');
